// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCitqJLydCImMy3Nxy3uyml2ua9t98rQTg',
    appId: '1:809897043776:web:bbbaeaea04330391a23ca5',
    messagingSenderId: '809897043776',
    projectId: 'somity-app-333311',
    authDomain: 'somity-app-333311.firebaseapp.com',
    storageBucket: 'somity-app-333311.firebasestorage.app',
    measurementId: 'G-RS3PD3R6HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXW6jh5l9ths0P5-7WMJcaIz5U7U7nT_4',
    appId: '1:809897043776:android:e2bcdfcfd84a0ab0a23ca5',
    messagingSenderId: '809897043776',
    projectId: 'somity-app-333311',
    storageBucket: 'somity-app-333311.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPa3XFJwjoXJKRIYIU1uV4CAl8mdZ8iIg',
    appId: '1:809897043776:ios:e453a8a7359485e2a23ca5',
    messagingSenderId: '809897043776',
    projectId: 'somity-app-333311',
    storageBucket: 'somity-app-333311.firebasestorage.app',
    iosBundleId: 'com.example.somitiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPa3XFJwjoXJKRIYIU1uV4CAl8mdZ8iIg',
    appId: '1:809897043776:ios:e453a8a7359485e2a23ca5',
    messagingSenderId: '809897043776',
    projectId: 'somity-app-333311',
    storageBucket: 'somity-app-333311.firebasestorage.app',
    iosBundleId: 'com.example.somitiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCitqJLydCImMy3Nxy3uyml2ua9t98rQTg',
    appId: '1:809897043776:web:08637253f42eaa55a23ca5',
    messagingSenderId: '809897043776',
    projectId: 'somity-app-333311',
    authDomain: 'somity-app-333311.firebaseapp.com',
    storageBucket: 'somity-app-333311.firebasestorage.app',
    measurementId: 'G-PHWRZXS5TS',
  );
}
